[fractal]
initial-length = 100
depth = 4
density = 6

[fractal.transform]
rotation = [
    [
        0.9698463,
        0.0301537,
        0.2418448,
    ],
    [
        0.0301537,
        0.9698463,
        -0.2418448,
    ],
    [
        -0.2418448,
        0.2418448,
        0.9396926,
    ],
]
scale = 0.1

[hemisphere]
radius = 4.1

[field]
width = 2.5
depth = 2.5
height = 1.25
spatial-res = 5e-3

[trial]
temporal-res = 5e-2
duration = 60
population = 20

[experiment]
num-trials = 32

[coeffs]
initial-scale = 0.03

[coeffs.bg]
diffusion = 1.0
absorption = 0.0

[coeffs.fg]
diffusion = 0.3
absorption = 0.7
